# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profanityFilter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15profanityFilter.proto\x12\'accelbyte.profanityfilter.registered.v1\"A\n ExtendProfanityValidationRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\"G\n!ExtendProfanityValidationResponse\x12\x11\n\tisProfane\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbc\x01\n\x16ProfanityFilterService\x12\xa1\x01\n\x08Validate\x12I.accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationRequest\x1aJ.accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationResponseB\x86\x01\n+net.accelbyte.profanityfilter.registered.v1P\x01Z+accelbyte.net/profanityfilter/registered_v1\xaa\x02\'AccelByte.ProfanityFilter.Registered.V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profanityFilter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+net.accelbyte.profanityfilter.registered.v1P\001Z+accelbyte.net/profanityfilter/registered_v1\252\002\'AccelByte.ProfanityFilter.Registered.V1'
  _EXTENDPROFANITYVALIDATIONREQUEST._serialized_start=66
  _EXTENDPROFANITYVALIDATIONREQUEST._serialized_end=131
  _EXTENDPROFANITYVALIDATIONRESPONSE._serialized_start=133
  _EXTENDPROFANITYVALIDATIONRESPONSE._serialized_end=204
  _PROFANITYFILTERSERVICE._serialized_start=207
  _PROFANITYFILTERSERVICE._serialized_end=395
# @@protoc_insertion_point(module_scope)
