# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import profanityFilter_pb2 as profanityFilter__pb2


class ProfanityFilterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/accelbyte.profanityfilter.registered.v1.ProfanityFilterService/Validate',
                request_serializer=profanityFilter__pb2.ExtendProfanityValidationRequest.SerializeToString,
                response_deserializer=profanityFilter__pb2.ExtendProfanityValidationResponse.FromString,
                )


class ProfanityFilterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfanityFilterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=profanityFilter__pb2.ExtendProfanityValidationRequest.FromString,
                    response_serializer=profanityFilter__pb2.ExtendProfanityValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.profanityfilter.registered.v1.ProfanityFilterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfanityFilterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.profanityfilter.registered.v1.ProfanityFilterService/Validate',
            profanityFilter__pb2.ExtendProfanityValidationRequest.SerializeToString,
            profanityFilter__pb2.ExtendProfanityValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
